"""OAuth2 authorization server endpoints for the Xiaodu (DuerOS) skill.

The Xiaodu smart-home skill acts as the OAuth2 *client*: it redirects the user
to our authorize endpoint and then exchanges the returned authorization code
at our token endpoint.

Design notes (least privilege + security):

- The authorize endpoint authenticates the user through Home Assistant's own
  login flow (in-process, via ``hass.auth.login_flow``), but the token issued
  to the Xiaodu skill is an *opaque* random string owned by this integration,
  NOT a Home Assistant user token. The DuerOS endpoint only exposes
  entities allowed by the entry's device/capability config, so a leaked token cannot be
  used against the Home Assistant API with user-level permissions.
- ``state`` is required and echoed back, and every authorization is bound to a
  short-lived server-side session nonce stored in a SameSite=Strict cookie, so
  the login form cannot be driven cross-site (login CSRF).
- The login flow is driven generically step by step, so multi-step flows
  (e.g. two-factor authentication) work: each form step is rendered from the
  flow's data schema.
- Access tokens are short-lived; refresh tokens last longer and are rotated.
- Tokens are persisted in HA storage so they survive restarts.

Values to configure on the Xiaodu developer console:

- Authorize URL: {base}/api/xiaodu/oauth/authorize
- Token URL:    {base}/api/xiaodu/oauth/token
- WebService:   {base}/api/xiaodu/service (DCS multipart + plain JSON)
- Callback URL: generated by the platform (read-only, must match the one
                stored in the config entry)
"""

from __future__ import annotations

import html
import json
import logging
import secrets
import time
from ipaddress import ip_address
from typing import Any
from urllib.parse import urlencode, urlparse

from aiohttp import web

from homeassistant.auth.models import AuthFlowContext
from homeassistant.components.auth import indieauth
from homeassistant.components.http import HomeAssistantView
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store

try:
    import voluptuous_serialize
except ImportError:  # pragma: no cover
    from homeassistant.helpers import voluptuous_serialize  # type: ignore[no-redef]

from .const import (
    CONF_CLIENT_ID,
    CONF_CLIENT_SECRET,
    CONF_REDIRECT_URI,
    DOMAIN,
    DUEROS_API_PATH,
    DUEROS_SERVICE_PATH,
    OAUTH_ACCESS_TOKEN_EXPIRE_SECONDS,
    OAUTH_AUTHORIZE_PATH,
    OAUTH_TOKEN_PATH,
)
from .dueros.dcs_envelope import fill_smarthome_response, parse_dcs_multipart
from .devices import build_device_map, summarize_devices
from .dueros import handle_request
from .dueros.constants import NAMESPACE_DISCOVERY, NAMESPACE_UNBIND
from .oauth_store import XiaoduOAuthStore

_LOGGER = logging.getLogger(__name__)


def _access_log(kind: str, **fields: Any) -> None:
    """Emit one INFO access-log line per external Xiaodu interaction."""
    detail = " ".join(
        f"{key}={value}" for key, value in fields.items() if value not in (None, "")
    )
    _LOGGER.info("Xiaodu access: kind=%s %s", kind, detail)

DATA_VIEWS_REGISTERED = "views_registered"
DATA_OAUTH_STORE = "oauth_store"
DATA_OAUTH_STORAGE = "oauth_storage"
STORAGE_KEY = "xiaodu.oauth_tokens"
STORAGE_VERSION = 1

# Session / CSRF protection
SESSION_COOKIE = "xiaodu_auth"
SESSION_TTL = 300
_auth_sessions: dict[str, dict[str, Any]] = {}

# Simple per-IP login throttle (the in-process login flow bypasses the
# http layer's built-in invalid-login tracking).
LOGIN_ATTEMPT_LIMIT = 5
LOGIN_ATTEMPT_WINDOW = 60
_failed_attempts: dict[str, list[float]] = {}

_FIXED_PARAMS = ("response_type", "client_id", "redirect_uri", "state")

# Allowed Xiaodu callback hosts (production + debug environment).
CALLBACK_HOSTS = ("xiaodu.baidu.com", "xiaodu-dbp.baidu.com")
_FIELD_LABELS = {
    "username": "用户名",
    "password": "密码",
    "code": "验证码",
    "otp": "验证码",
    "totp": "动态验证码",
}
_SUBTITLE_LOGIN = "请使用 Home Assistant 账号登录，以完成小度技能绑定。"
_SUBTITLE_MFA = "请输入第二步验证信息。"

_PAGE = """<!doctype html>
<html lang="zh-CN">
<head><meta charset="utf-8"><title>小度授权</title></head>
<body style="font-family:system-ui,sans-serif;max-width:380px;margin:80px auto">
<h2>小度授权</h2>
<p>授权小度访问 <strong>__ENTITY_SUMMARY__</strong>（可在集成选项中调整包含/排除范围）。</p>
<p>__SUBTITLE__</p>
<form method="post" action="__ACTION__">
<input type="hidden" name="response_type" value="code">
<input type="hidden" name="client_id" value="__CLIENT_ID__">
<input type="hidden" name="redirect_uri" value="__REDIRECT_URI__">
<input type="hidden" name="state" value="__STATE__">
__FIELDS__
__ERROR__
<p><button type="submit" style="padding:8px 24px">__SUBMIT__</button></p>
</form>
</body>
</html>
"""


def _esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def _get_entry(hass: HomeAssistant) -> ConfigEntry | None:
    """Return the single Xiaodu config entry, if any."""
    entries = hass.config_entries.async_entries(DOMAIN)
    return entries[0] if entries else None


def _callback_origin(redirect_uri: str) -> str:
    """Return the scheme://netloc of the callback URL (used as OAuth client id)."""
    parts = urlparse(redirect_uri)
    return f"{parts.scheme}://{parts.netloc}"


def _redirect_uri_allowed(requested: str, configured: str) -> bool:
    """Accept the configured callback, or the same path on a known Xiaodu host.

    The Xiaodu console uses ``xiaodu.baidu.com`` in production and
    ``xiaodu-dbp.baidu.com`` for debug / mock testing; both are accepted so
    the console environment does not require a reconfigure.
    """
    if requested == configured:
        return True
    try:
        req = urlparse(requested)
        conf = urlparse(configured)
    except ValueError:
        return False
    return (
        req.scheme == "https"
        and (req.hostname or "") in CALLBACK_HOSTS
        and req.path == conf.path
        and not req.query
    )


async def _get_store(hass: HomeAssistant) -> XiaoduOAuthStore:
    """Return the shared OAuth store, loading persisted tokens on first use."""
    data = hass.data.setdefault(DOMAIN, {})
    if DATA_OAUTH_STORE not in data:
        store = XiaoduOAuthStore()
        storage = Store[dict[str, Any]](hass, STORAGE_VERSION, STORAGE_KEY)
        store.load_dict(await storage.async_load())
        data[DATA_OAUTH_STORE] = store
        data[DATA_OAUTH_STORAGE] = storage
    return data[DATA_OAUTH_STORE]


async def _save_store(hass: HomeAssistant) -> None:
    """Persist the current token store."""
    storage: Store[dict[str, Any]] = hass.data[DOMAIN][DATA_OAUTH_STORAGE]
    store: XiaoduOAuthStore = hass.data[DOMAIN][DATA_OAUTH_STORE]
    await storage.async_save(store.to_dict())


def _exposed_device_summary(hass: HomeAssistant, entry: ConfigEntry) -> str:
    """Return a human-readable summary of devices exposed to Xiaodu."""
    return summarize_devices(build_device_map(hass, entry.options))


# ---------------------------------------------------------------------------
# Session / CSRF helpers
# ---------------------------------------------------------------------------


def _new_session() -> str:
    """Create a short-lived authorization session and return its nonce."""
    nonce = secrets.token_urlsafe(24)
    _auth_sessions[nonce] = {"flow_id": None, "expires_at": time.time() + SESSION_TTL}
    return nonce


def _get_session(nonce: str) -> dict[str, Any] | None:
    session = _auth_sessions.get(nonce)
    if session is None or session["expires_at"] <= time.time():
        _auth_sessions.pop(nonce, None)
        return None
    return session


def _delete_session(nonce: str) -> None:
    _auth_sessions.pop(nonce, None)


def _login_throttled(remote_addr: str) -> bool:
    """Return True when the client has too many recent failed attempts."""
    now = time.time()
    attempts = [
        t for t in _failed_attempts.get(remote_addr, []) if now - t < LOGIN_ATTEMPT_WINDOW
    ]
    _failed_attempts[remote_addr] = attempts
    return len(attempts) >= LOGIN_ATTEMPT_LIMIT


def _record_failure(remote_addr: str) -> None:
    _failed_attempts.setdefault(remote_addr, []).append(time.time())


def _clear_failures(remote_addr: str) -> None:
    _failed_attempts.pop(remote_addr, None)


# ---------------------------------------------------------------------------
# Form rendering
# ---------------------------------------------------------------------------


def _schema_fields(schema: Any) -> list[dict[str, Any]]:
    """Convert a flow data schema into renderable fields."""
    if schema is None:
        return []
    try:
        return voluptuous_serialize.convert(schema)
    except Exception:  # noqa: BLE001 - never break the authorize page
        return []


def _render_field(field: dict[str, Any]) -> str:
    name = str(field.get("name", ""))
    label = _FIELD_LABELS.get(name, name)
    ftype = field.get("type", "string")
    default = field.get("default", "")
    if ftype == "boolean":
        checked = " checked" if default else ""
        return (
            f'<p><label><input type="checkbox" name="{_esc(name)}"{checked}> '
            f"{_esc(label)}</label></p>"
        )
    input_type = (
        "password"
        if "password" in name.lower()
        else ("number" if ftype == "integer" else "text")
    )
    value = _esc(default) if default not in (None, "") else ""
    return (
        f'<p><label>{_esc(label)}<br>'
        f'<input name="{_esc(name)}" type="{input_type}" value="{value}" '
        f'style="width:100%"></label></p>'
    )


def _render_fields(fields: list[dict[str, Any]]) -> str:
    if not fields:
        fields = [
            {"name": "username", "type": "string", "required": True},
            {"name": "password", "type": "string", "required": True},
        ]
    return "".join(_render_field(field) for field in fields)


def _map_errors(errors: dict[str, Any] | None) -> str:
    if not errors:
        return ""
    base = str(errors.get("base", ""))
    if base in ("invalid_auth",):
        return "用户名或密码错误"
    if base in ("invalid_code",):
        return "验证码错误"
    return "登录失败，请重试"


class XiaoduOAuthAuthorizeView(HomeAssistantView):
    """Handle requests to the OAuth2 authorize endpoint."""

    url = OAUTH_AUTHORIZE_PATH
    name = "api:xiaodu:oauth:authorize"
    requires_auth = False

    async def get(self, request: web.Request) -> web.Response:
        """Show the first login/consent page."""
        return await self._handle(request, submitted=False)

    async def post(self, request: web.Request) -> web.Response:
        """Progress the login flow and redirect back on success."""
        return await self._handle(request, submitted=True)

    async def _handle(self, request: web.Request, submitted: bool) -> web.Response:
        hass = request.app["hass"]
        entry = _get_entry(hass)
        if entry is None:
            return web.Response(text="Xiaodu is not configured.", status=400)

        params = dict(request.query)
        if submitted:
            params.update(await request.post())

        client_id = entry.data.get(CONF_CLIENT_ID)
        configured_redirect = entry.data.get(CONF_REDIRECT_URI)
        redirect_uri = params.get("redirect_uri", "")
        state = params.get("state", "")

        # ``state`` is required (Xiaodu always sends it) and validated on
        # every step of the flow. The redirect URI may use either the
        # production or the debug Xiaodu host.
        if (
            params.get("response_type") != "code"
            or params.get("client_id") != client_id
            or not _redirect_uri_allowed(redirect_uri, configured_redirect)
            or not state
        ):
            return web.Response(text="Invalid authorization request.", status=400)

        summary = _exposed_device_summary(hass, entry)

        if not submitted:
            nonce = _new_session()
            return self._page(
                client_id,
                redirect_uri,
                state,
                summary=summary,
                fields=[],
                subtitle=_SUBTITLE_LOGIN,
                submit="登录并授权",
                error="",
                nonce=nonce,
            )

        remote_addr = request.remote or ""
        if _login_throttled(remote_addr):
            return self._page(
                client_id,
                redirect_uri,
                state,
                summary=summary,
                fields=[],
                subtitle=_SUBTITLE_LOGIN,
                submit="登录并授权",
                error="尝试次数过多，请稍后再试",
                nonce="",
            )

        nonce = request.cookies.get(SESSION_COOKIE, "")
        session = _get_session(nonce)
        if session is None:
            return web.Response(text="授权会话已过期，请重新打开授权页。", status=400)

        try:
            result = await self._progress_flow(
                hass, request, redirect_uri, session, params
            )
        except (ValueError, KeyError) as err:
            _LOGGER.warning("Xiaodu authorize flow failed: %s", err)
            _delete_session(nonce)
            return self._page(
                client_id,
                redirect_uri,
                state,
                summary=summary,
                fields=[],
                subtitle=_SUBTITLE_LOGIN,
                submit="登录并授权",
                error="授权流程异常，请重新打开授权页",
                nonce="",
            )

        if result["type"] == "create_entry":
            credentials = result.get("result")
            if credentials is None:
                _delete_session(nonce)
                return self._page(
                    client_id,
                    redirect_uri,
                    state,
                    summary=summary,
                    fields=[],
                    subtitle=_SUBTITLE_LOGIN,
                    submit="登录并授权",
                    error="登录未完成，请重试",
                    nonce="",
                )
            user = await hass.auth.async_get_user_by_credentials(credentials)
            user_id = user.id if user else ""
            _clear_failures(remote_addr)
            _delete_session(nonce)
            _LOGGER.info("Xiaodu bound by user %s", user_id or "unknown")

            store = await _get_store(hass)
            code = store.issue_code(client_id, redirect_uri, user_id)
            query = {"code": code}
            if state:
                query["state"] = state
            response = web.HTTPFound(f"{redirect_uri}?{urlencode(query)}")
            response.headers["Set-Cookie"] = _clear_cookie()
            return response

        if result["type"] == "form":
            fields = _schema_fields(result.get("data_schema"))
            error = _map_errors(result.get("errors"))
            if error:
                _record_failure(remote_addr)
            is_login = bool(fields) and fields[0].get("name") in ("username", "password")
            return self._page(
                client_id,
                redirect_uri,
                state,
                summary=summary,
                fields=fields,
                subtitle=_SUBTITLE_LOGIN if is_login else _SUBTITLE_MFA,
                submit="登录并授权" if is_login else "继续",
                error=error,
                nonce=nonce,
            )

        # aborted / unexpected
        _delete_session(nonce)
        return self._page(
            client_id,
            redirect_uri,
            state,
            summary=summary,
            fields=[],
            subtitle=_SUBTITLE_LOGIN,
            submit="登录并授权",
            error="授权已取消，请重试",
            nonce="",
        )

    @staticmethod
    async def _progress_flow(
        hass: HomeAssistant,
        request: web.Request,
        redirect_uri: str,
        session: dict[str, Any],
        params: dict[str, Any],
    ) -> dict[str, Any]:
        """Start or advance the login flow and return the raw flow result."""
        flow_mgr = hass.auth.login_flow
        client_id_origin = _callback_origin(redirect_uri)
        if not indieauth.verify_client_id(client_id_origin):
            raise ValueError("invalid client id")

        if session.get("flow_id") is None:
            result = await flow_mgr.async_init(
                ("homeassistant", None),
                context=AuthFlowContext(
                    ip_address=ip_address(request.remote),
                    redirect_uri=redirect_uri,
                ),
            )
            if result.get("type") != "form":
                raise ValueError(result.get("errors") or "login flow did not start")
            session["flow_id"] = result["flow_id"]

        user_input = {
            key: value
            for key, value in params.items()
            if key not in _FIXED_PARAMS
        }
        return await flow_mgr.async_configure(session["flow_id"], user_input)

    @staticmethod
    def _page(
        client_id: str,
        redirect_uri: str,
        state: str,
        summary: str,
        fields: list[dict[str, Any]],
        subtitle: str,
        submit: str,
        error: str,
        nonce: str,
    ) -> web.Response:
        page = (
            _PAGE.replace("__ACTION__", _esc(OAUTH_AUTHORIZE_PATH))
            .replace("__CLIENT_ID__", _esc(client_id or ""))
            .replace("__REDIRECT_URI__", _esc(redirect_uri or ""))
            .replace("__STATE__", _esc(state))
            .replace("__ENTITY_SUMMARY__", _esc(summary))
            .replace("__SUBTITLE__", _esc(subtitle))
            .replace("__FIELDS__", _render_fields(fields))
            .replace("__SUBMIT__", _esc(submit))
            .replace(
                "__ERROR__",
                f'<p style="color:#c62828">{_esc(error)}</p>' if error else "",
            )
        )
        headers = {}
        if nonce:
            headers["Set-Cookie"] = (
                f"{SESSION_COOKIE}={nonce}; Path={OAUTH_AUTHORIZE_PATH}; "
                f"HttpOnly; SameSite=Strict; Max-Age={SESSION_TTL}"
            )
        else:
            headers["Set-Cookie"] = _clear_cookie()
        return web.Response(
            text=page, content_type="text/html", charset="utf-8", headers=headers
        )


def _clear_cookie() -> str:
    return f"{SESSION_COOKIE}=; Path={OAUTH_AUTHORIZE_PATH}; Max-Age=0"


class XiaoduOAuthTokenView(HomeAssistantView):
    """Handle requests to the OAuth2 token endpoint."""

    url = OAUTH_TOKEN_PATH
    name = "api:xiaodu:oauth:token"
    requires_auth = False

    async def post(self, request: web.Request) -> web.Response:
        """Exchange a code or refresh token for an opaque access token."""
        hass = request.app["hass"]
        entry = _get_entry(hass)
        if entry is None:
            return web.json_response({"error": "invalid_client"}, status=400)

        data = await self._parse_data(request)
        status, body = await self._exchange(hass, entry, data)
        _access_log(
            "token",
            grant_type=data.get("grant_type"),
            client_id=data.get("client_id"),
            status=status,
            result=body.get("error", "ok"),
        )
        return web.json_response(body, status=status)

    @staticmethod
    async def _exchange(
        hass: HomeAssistant, entry: ConfigEntry, data: dict[str, Any]
    ) -> tuple[int, dict[str, Any]]:
        """Perform the token exchange; return (http_status, body)."""
        if (
            data.get("client_id") != entry.data.get(CONF_CLIENT_ID)
            or data.get("client_secret") != entry.data.get(CONF_CLIENT_SECRET)
        ):
            return 400, {"error": "invalid_client"}

        store = await _get_store(hass)
        grant_type = data.get("grant_type")

        if grant_type == "authorization_code":
            code = data.get("code")
            record = store.consume_code(code) if code else None
            if record is None or data.get("redirect_uri") != record["redirect_uri"]:
                return 400, {"error": "invalid_grant"}
            access, refresh = store.issue_token(
                record["client_id"], record.get("user_id")
            )
        elif grant_type == "refresh_token":
            rotated = store.rotate_token(data.get("refresh_token", ""))
            if rotated is None:
                return 400, {"error": "invalid_grant"}
            access, refresh = rotated
        else:
            return 400, {"error": "unsupported_grant_type"}

        await _save_store(hass)
        return 200, {
            "access_token": access,
            "token_type": "Bearer",
            "expires_in": OAUTH_ACCESS_TOKEN_EXPIRE_SECONDS,
            "refresh_token": refresh,
        }

    @staticmethod
    async def _parse_data(request: web.Request) -> dict[str, Any]:
        if request.content_type == "application/json":
            try:
                return await request.json()
            except (json.JSONDecodeError, ValueError):
                pass
        return dict(await request.post())


async def _process_dueros_request(
    hass: HomeAssistant,
    request: web.Request,
    data: dict[str, Any],
    started: float,
) -> dict[str, Any]:
    """Validate the token and dispatch one DuerOS smart-home request.

    Shared by the plain JSON endpoint (``/api/xiaodu``) and the Baidu console
    DCS multipart endpoint (``/api/xiaodu/service``). Returns the response
    dict; the caller decides how to serialize it.
    """
    store = await _get_store(hass)
    header = data.get("header") or {}
    payload = data.get("payload") or {}
    message_id = header.get("messageId", "")
    namespace = header.get("namespace", "")
    name = header.get("name", "")
    entity_id = (payload.get("appliance") or {}).get("applianceId", "")

    token = payload.get("accessToken") or ""
    if not token:
        auth = request.headers.get("Authorization", "")
        if auth.lower().startswith("bearer "):
            token = auth[7:].strip()

    if not store.validate_token(token):
        _LOGGER.warning(
            "Xiaodu DuerOS request rejected (invalid token), messageId=%s",
            message_id,
        )
        _log_dueros(
            request, started, message_id, namespace, name, entity_id,
            result="ACCESS_TOKEN_INVALIDATE", status=401,
        )
        return {"error": "ACCESS_TOKEN_INVALIDATE"}

    entry = _get_entry(hass)
    if entry is None:
        _log_dueros(
            request, started, message_id, namespace, name, entity_id,
            result="ACCESS_TOKEN_INVALIDATE", status=401,
        )
        return {"error": "ACCESS_TOKEN_INVALIDATE"}

    if namespace == NAMESPACE_UNBIND and name == "UnbindBotRequest":
        # User unbundled the skill in the Xiaodu store: revoke the token and
        # drop the openUid bound to that user so device sync stops targeting
        # them. user_id must be read before the token record is revoked.
        user_id = store.user_id_for_token(token)
        store.revoke(token)
        if user_id:
            store.remove_open_uid(user_id)
        await _save_store(hass)
        _log_dueros(
            request, started, message_id, namespace, name, entity_id,
            result="UnbindBotResponse", status=200,
        )
        response_header = dict(header)
        response_header["name"] = "UnbindBotResponse"
        return {"header": response_header, "payload": {}}

    open_uid = payload.get("openUid") or ""
    if namespace == NAMESPACE_DISCOVERY and open_uid:
        user_id = store.user_id_for_token(token)
        if store.record_open_uid(user_id, open_uid):
            await _save_store(hass)
            _LOGGER.info("Xiaodu recorded openUid %s (user %s)", open_uid, user_id or "?")

    devices = build_device_map(hass, entry.options)

    try:
        response = await handle_request(hass, devices, data)
        result = (response.get("header") or {}).get("name", "OK")
        status = 200
    except Exception:  # noqa: BLE001 - protocol errors must not 500 the skill
        _LOGGER.exception(
            "Xiaodu DuerOS request failed, messageId=%s",
            message_id,
        )
        response_header = dict(header)
        response_header["name"] = "DriverInternalError"
        response = {"header": response_header, "payload": {}}
        result = "DriverInternalError"
        status = 200

    _log_dueros(
        request, started, message_id, namespace, name, entity_id,
        result=result, status=status,
    )
    return response


def _log_dueros(
    request: web.Request,
    started: float,
    message_id: str,
    namespace: str,
    name: str,
    entity_id: str,
    result: str,
    status: int,
) -> None:
    """Emit one access-log line for a DuerOS request."""
    duration_ms = round((time.perf_counter() - started) * 1000, 1)
    _access_log(
        "dueros",
        messageId=message_id,
        namespace=namespace,
        name=name,
        entity=entity_id,
        result=result,
        status=status,
        ms=duration_ms,
        ip=request.remote,
        xff=request.headers.get("X-Forwarded-For", "").split(",")[0].strip(),
    )


class XiaoduDuerOSView(HomeAssistantView):
    """Plain-JSON DuerOS smart-home endpoint (production shape).

    The Xiaodu skill authenticates every request with the opaque access token
    it received at the token endpoint; the token travels inside the JSON
    payload (``payload.accessToken``), with the ``Authorization`` header kept
    as a fallback. Even with a valid token, requests only operate on entities
    allowed by the entry's device/capability config (least privilege).
    """

    url = DUEROS_API_PATH
    name = "api:xiaodu:dueros"
    requires_auth = False

    async def post(self, request: web.Request) -> web.Response:
        """Handle a plain-JSON DuerOS smart-home request."""
        hass = request.app["hass"]
        started = time.perf_counter()
        data = await _parse_json(request)
        if data is None:
            _access_log(
                "dueros",
                result="INVALID_REQUEST",
                status=400,
                ms=round((time.perf_counter() - started) * 1000, 1),
                ip=request.remote,
                xff=request.headers.get("X-Forwarded-For", "").split(",")[0].strip(),
            )
            return web.json_response({"error": "INVALID_REQUEST"}, status=400)
        response = await _process_dueros_request(hass, request, data, started)
        status = 401 if response.get("error") else 200
        return web.json_response(response, status=status)


class XiaoduDuerOSServiceView(HomeAssistantView):
    """WebService endpoint (``/api/xiaodu/service``) for the Xiaodu console.

    Accepts both shapes:

    - ``application/json``: the production smart-home directive, handled
      exactly like :class:`XiaoduDuerOSView`.
    - ``multipart/form-data``: the Baidu console "模拟测试" DCS envelope.
      The real directive is read from ``metadata.debug.bot.smarthome[0]``,
      processed, and the response is written back to the same slot.
    """

    url = DUEROS_SERVICE_PATH
    name = "api:xiaodu:dueros:service"
    requires_auth = False

    async def post(self, request: web.Request) -> web.Response:
        """Handle a request to the WebService endpoint."""
        hass = request.app["hass"]
        started = time.perf_counter()

        if request.content_type == "application/json":
            data = await _parse_json(request)
            if data is None:
                return _invalid_request(started, request)
            response = await _process_dueros_request(hass, request, data, started)
            status = 401 if response.get("error") else 200
            return web.json_response(response, status=status)

        if request.content_type.startswith("multipart/form-data"):
            envelope = parse_dcs_multipart(
                await request.read(), request.headers.get("Content-Type", "")
            )
            if envelope is None:
                # No smart-home directive inside the DCS envelope (e.g. a pure
                # TTS/audio exchange); acknowledge so the gateway can proceed.
                _access_log(
                    "dueros",
                    result="NO_SMARTHOME_REQUEST",
                    status=200,
                    ms=round((time.perf_counter() - started) * 1000, 1),
                    ip=request.remote,
                    xff=request.headers.get(
                        "X-Forwarded-For", ""
                    ).split(",")[0].strip(),
                )
                return web.json_response({})
            response = await _process_dueros_request(
                hass, request, envelope["smarthome"], started
            )
            if response.get("error"):
                # Token rejection is a hard error for the whole request.
                return web.json_response(response, status=401)
            filled = fill_smarthome_response(envelope["metadata"], response)
            return web.json_response(filled)

        return _invalid_request(started, request)
async def _parse_json(request: web.Request) -> dict[str, Any] | None:
    """Parse the DuerOS JSON body (None when malformed)."""
    try:
        data = await request.json()
    except (json.JSONDecodeError, ValueError):
        return None
    return data if isinstance(data, dict) else None


def _invalid_request(started: float, request: web.Request) -> web.Response:
    """Log and return a 400 INVALID_REQUEST response."""
    _access_log(
        "dueros",
        result="INVALID_REQUEST",
        status=400,
        ms=round((time.perf_counter() - started) * 1000, 1),
        ip=request.remote,
        xff=request.headers.get("X-Forwarded-For", "").split(",")[0].strip(),
    )
    return web.json_response({"error": "INVALID_REQUEST"}, status=400)
