"""OAuth2 authorization server endpoints for the xiaodu skill.

The Xiaodu smart-home skill acts as the OAuth2 *client*: it redirects the user
to our authorize endpoint and then exchanges the returned authorization code
at our token endpoint.

Design notes (least privilege + security):

- The authorize endpoint authenticates the user through Home Assistant's own
  login flow (in-process, via ``hass.auth.login_flow``), but the token issued
  to the Xiaodu skill is an *opaque* random string owned by this integration,
  NOT a Home Assistant user token. The DuerOS endpoint only exposes
  entities allowed by the entry's device/capability config, so a leaked token cannot be
  used against the Home Assistant API with user-level permissions.
- ``state`` is required and echoed back, and every authorization is bound to a
  short-lived server-side session nonce stored in a SameSite=Strict cookie, so
  the login form cannot be driven cross-site (login CSRF).
- The login flow is driven generically step by step, so multi-step flows
  (e.g. two-factor authentication) work: each form step is rendered from the
  flow's data schema.
- Access tokens are short-lived; refresh tokens last longer and are rotated.
- Tokens are persisted in HA storage so they survive restarts.

Values to configure on the Xiaodu developer console:

- Authorize URL: {base}/api/xiaodu/oauth/authorize
- Token URL:    {base}/api/xiaodu/oauth/token
- WebService:   {base}/api/xiaodu/service (DCS multipart + plain JSON)
- Callback URL: generated by the platform (read-only, must match the one
                stored in the config entry)
"""

from __future__ import annotations

import html
import json
import logging
import secrets
import time
from ipaddress import ip_address
from typing import Any
from urllib.parse import urlencode, urlparse

from aiohttp import web

from homeassistant.auth.models import AuthFlowContext
from homeassistant.components.auth import indieauth
from homeassistant.components.http import HomeAssistantView
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.storage import Store

try:
    import voluptuous_serialize
except ImportError:  # pragma: no cover
    from homeassistant.helpers import voluptuous_serialize  # type: ignore[no-redef]

from .const import (
    CONF_CLIENT_ID,
    CONF_CLIENT_SECRET,
    CONF_REDIRECT_URI,
    DATA_ENHANCED_DEVICES,
    DOMAIN,
    DUEROS_API_PATH,
    DUEROS_SERVICE_PATH,
    OAUTH_ACCESS_TOKEN_EXPIRE_SECONDS,
    OAUTH_AUTHORIZE_PATH,
    OAUTH_TOKEN_PATH,
)
from .dueros.dcs_envelope import fill_smarthome_response, parse_dcs_multipart
from .devices import CAP_LABELS
from .dueros import handle_request
from .dueros.constants import NAMESPACE_DISCOVERY, NAMESPACE_UNBIND
from .oauth_store import XiaoduOAuthStore

_LOGGER = logging.getLogger(__name__)


def _access_log(kind: str, **fields: Any) -> None:
    """Emit one INFO access-log line per external Xiaodu interaction."""
    detail = " ".join(
        f"{key}={value}" for key, value in fields.items() if value not in (None, "")
    )
    _LOGGER.info("Xiaodu access: kind=%s %s", kind, detail)

DATA_VIEWS_REGISTERED = "views_registered"
DATA_OAUTH_STORE = "oauth_store"
DATA_OAUTH_STORAGE = "oauth_storage"
DATA_AUTH_SESSIONS = "auth_sessions"
DATA_FAILED_ATTEMPTS = "failed_attempts"
STORAGE_KEY = "xiaodu.oauth_tokens"
STORAGE_VERSION = 1

# Session / CSRF protection
SESSION_COOKIE = "xiaodu_auth"
SESSION_TTL = 300

# Simple per-IP login throttle (the in-process login flow bypasses the
# http layer's built-in invalid-login tracking).
LOGIN_ATTEMPT_LIMIT = 5
LOGIN_ATTEMPT_WINDOW = 60

_FIXED_PARAMS = ("response_type", "client_id", "redirect_uri", "state")

# Allowed Xiaodu callback hosts (production + debug environment).
CALLBACK_HOSTS = ("xiaodu.baidu.com", "xiaodu-dbp.baidu.com")
_FIELD_LABELS = {
    "username": "用户名",
    "password": "密码",
    "code": "验证码",
    "otp": "验证码",
    "totp": "动态验证码",
}
_SUBTITLE_LOGIN = "请使用 Home Assistant 账号登录，以完成小度技能绑定。"
_SUBTITLE_MFA = "请输入第二步验证信息。"

_PAGE = """<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>小度授权</title>
<style>
:root {
  --bg: #f0f2f5;
  --card: #ffffff;
  --text: #1f2329;
  --muted: #6b7280;
  --border: #d9dee5;
  --primary: #1668dc;
  --primary-hover: #0f5bc0;
  --primary-ring: rgba(22, 104, 220, 0.18);
  --danger: #d4380d;
  --danger-bg: #fff1f0;
  --danger-border: #ffccc7;
  --input-bg: #ffffff;
  --summary-bg: #f6f8fb;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #131414;
    --card: #1f2021;
    --text: #e8eaed;
    --muted: #9aa0a6;
    --border: #3c4043;
    --primary: #4c8bf5;
    --primary-hover: #6ba1f7;
    --primary-ring: rgba(76, 139, 245, 0.25);
    --danger: #ff7875;
    --danger-bg: #2a1215;
    --danger-border: #5c1a1a;
    --input-bg: #2a2b2c;
    --summary-bg: #262728;
  }
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, "PingFang SC",
    "Microsoft YaHei", sans-serif;
  background: var(--bg);
  color: var(--text);
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 24px;
  -webkit-font-smoothing: antialiased;
}
.card {
  background: var(--card);
  border: 1px solid var(--border);
  border-radius: 16px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.08);
  padding: 36px 32px;
  width: 100%;
  max-width: 400px;
}
.brand {
  font-size: 20px;
  font-weight: 600;
  margin-bottom: 20px;
  display: flex;
  align-items: center;
  gap: 9px;
}
.logo {
  width: 28px;
  height: 28px;
  border-radius: 7px;
  flex-shrink: 0;
}
.summary {
  background: var(--summary-bg);
  border-radius: 10px;
  padding: 12px 14px;
  font-size: 13px;
  color: var(--muted);
  line-height: 1.6;
  margin-bottom: 8px;
}
.summary strong { color: var(--text); font-weight: 600; }
.summary-hint { margin-top: 6px; font-size: 12px; }
.subtitle {
  font-size: 14px;
  color: var(--muted);
  margin: 8px 0 20px;
}
.field { display: block; margin-bottom: 16px; }
.field-label {
  display: block;
  font-size: 13px;
  color: var(--muted);
  margin-bottom: 6px;
}
.input {
  width: 100%;
  padding: 10px 12px;
  font-size: 15px;
  color: var(--text);
  background: var(--input-bg);
  border: 1px solid var(--border);
  border-radius: 8px;
  outline: none;
  transition: border-color .15s, box-shadow .15s;
}
.input:focus {
  border-color: var(--primary);
  box-shadow: 0 0 0 3px var(--primary-ring);
}
.field-check {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  cursor: pointer;
}
.field-check input { width: 16px; height: 16px; accent-color: var(--primary); }
.error {
  background: var(--danger-bg);
  border: 1px solid var(--danger-border);
  color: var(--danger);
  border-radius: 8px;
  padding: 10px 12px;
  font-size: 13px;
  margin-bottom: 16px;
}
.submit {
  width: 100%;
  padding: 12px;
  font-size: 15px;
  font-weight: 600;
  color: #fff;
  background: var(--primary);
  border: none;
  border-radius: 8px;
  cursor: pointer;
  margin-top: 4px;
  transition: background .15s;
}
.submit:hover { background: var(--primary-hover); }
.submit:active { transform: translateY(1px); }
</style>
</head>
<body>
<main class="card">
  <div class="brand">
    <img class="logo" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAZcElEQVR42o2bebBkV33fP79zb3e/bd6bTRotM5JmBiEJLZaChJCEWA0CYRJEEIEUCsSkUk7FiaEU2xXHjq1gKkXiVKVIuUw5sVNgQ1zEKTAxJikryDYUIFtIQhISIwlto1k189be7nLOL3+cc+49t98olanq6e7Xt2+fc3779/f9yRVfs6oIiiLhWRUE/0/xr2X2Dxoe4W+KIBr+pPjX4Znwuvk77fcFmt/T5H7MfFcVcOAcqAVrwdVga3BWcVZwNlzr2t+Ly40/qmEfgoCA8Rf6zaOKKIiIv17itwVUwgKlubGCv6G0Z0Kyh/RZks8kfdb2uyIz1wrNgv+//kl7epKcoDZSkbAlQcNnRjQRbdisqCanRisKkbBh/x2RsMIooXA4otKRYPpQWul01p5oSfys0SAvnpmvnOtktPtR8rbRuvBOVFAVcgmrUqLkNaiNJL/hVUfCZ+1Cg+Y0l2nYiJ5TIyT5rtAeSLNQfbUD0eYw0r/NHmKz4PSmgIo2R6iN4Pz9chLVUxdfx60GdSFINdxdOkes4WbarCmaU6sN2jz7zUtnAxJ8iN9dMDWdMR7VV5e+bntBKoK44Wbl0R8AORrsPdqNCki7ydYh+s9EBNVUlyVsXhLnp9tek5iVxs1od2+tE9RGXdVp62xUwUnjEFsVonvNOQxDRBshRg0FIRdpb+LtWzuq2CwkvnFRlbW1/+Ryl6qndiXWePNGE9L1hvuhrao3coyhwAvHSHNpogua2PhsuIqC1NYnSDAB1db2RVvV9xqpiQkE76CJnakLu/aLVBfs2AW7jYtxIdC61rGJptJpnZ26sMgYyqL6uiDFsL28p4gYNjfBZEHNO5JshalBjVVDoJf2mlzCj4pI5yAT/+e/FOy5kYbTxgQIm27idvNaWym7bqRS14bPVos00RK/cIOiLomP8RANGByuEmwVDiGT1gFq4gskNZXwo+J/K1d9lZDSJC3a2ixh487bYrP5KLFUws77hUYR3UxYcp2o1DomleaaJgRKuD4eonhH6vAHIQrUzh+USRVdEnNubUYSCeeirf2p6HbvoRq0UKF2QU0Bq413JcnUJNGEqMbRXnEhlzhHLqBWw8bahAWVbgxPw6TprjNmotgQykRazxX9SRqbgxPINVX4Jiyl9kSi8nFTYYEObz4xAjgNUora4dW30aSwtkahXJoKJuobDlxUcFGeKt0AATi7zdd5qTsf+5ssNgmFHTfROEG6+43pUIzdTSizSTgLOTm0oS6quYaEqHGGro33RuIGJXwunUxTNLoLCZsVjLRZVDxsnFJOfW1gTLu5eMCiihppTCaN/WnSlUcPLp2Aom28jtIPi/USpz2Q6CAd3gbD62jD1kJtoa7DswWbeGZx0c4VI4oxkBull0PfQJZJE1FUvHTF+GXVU0nOLskRguDFaVAsmfFyrT/Io3eORxUzuqhvGqXUVFgCVpt4ripgg/QdGGBawGgClYWBgeUBnD8PO+dh1wAW52CQQx4cmEMpLUxKWB/D2QmcGcH6UCkczPVgaV7Jc7AqGIVqCtVUySSmcJ1kt+svzp0wx0ywK3XphC5t7LxJi22I57bN/rBgHGxNYDyFi3bAWy+HN14CV+9T9q/AngVY6EO/J0EnZXsu65SiVsYlnBkqL64Jjx6Hv3gWHjqqFCrsWgJ6MN4AVwnS86YY7T51CRLjv3gN09k0SUGu/INaW9tP0lwUtdpIXgGj/jDUArV3uAawFZzZVF53nvCJm4Q7r3Ds3y34UsN0Tr90UJSOurYha/Sal2WGPDf0cuiZ9lvqLJvjmkdfht//a8M3jnhVtyMficWAmCZdC7E7+P8QdRBpaxyRToUoV3yhjuVJsLXoEzzQgKq3U42Oz4MP6rzUJyWUU/jU7cI/vcWxvJADGQ54+fgazz5/gp+8eJKXjp3l5CsbrK2P2ByOmExLbG1x1mIyYTDoszAYsLw8z4Xn7+TSA/t4zaFLeO1rLmHf+Uv0DRSTgj8/Itz7BXh5E1Z2ChYwBiRLIgJJiR7fyzkMQgS54vfrJhcSJQEQYvhrawB1oLU/AKy39QHwux8QfvpKBfqcXh3yv7/1MA989ymefu4Mp1eHjKcV1jlUHeoszllceO9sjbM11jqsranrGmcrwDHXz7j4gt3cdvO1fOiuO7jpptcxwPLMsZp/+Hl48gzsWDE+kORN1hyqzbSglCbTTYp9nxtc8V+qbfVTW9OHbC7aQN3aflVAPYWv3AO3HTJUmvPlrzzAl772NwzrOXqDBZx1VMWEsphSVSVVNaWuCuq6xjrFWa8BzllULagNqbBFsbi6ppgWTEZD+v2cD9/10/zSL/4c+/Ys8sKJig/+B+VkaZhfFDSL5tAGeU3gpIhySVJiCYJc8bul6iyEotLmtCECONVwAN7hnF4TPvc+5WM3G7Ymyq98+g94/PktXnfdNYyGBSdPnGZjbY3JeERVFVS2xtoKW1XUtfNaYIMWOIdSo86hqqjWQd18eBHAupqt02e44YYr+fzvfJaDB3Zz/yM1H/8dZW6n8RqQCZK1km9whhT0aOqRiAm6kJDEWO98rFdm0JikPljdgncchHtuhKLO+Jf/5os8cbTklttv5uzZdY6+dIy11VWGoyHTYkxZT6nKgrqKql7hXIVzNc7VqJaos/6hdQi/DufAOaW2/rB2nr+XRx55ik/e+xuc2ah58zXCXa9XNtccYoN22i4UJ2hbmDWZrIaHw7TJTixm1IcPq2DFu1rVJtbbGsQKv3C7w2R9vvTHf8m3/uYYlx08yKOPHOHYSydZX11luLVBWU2pcNTOUTtLVZfUdYFzFdZav3lXB5/gzUCd9YdvDGqMl0vQjKKs2LF3F9/7ywf50h/+MYP5Ph95EyyIUhVBYWysQ0Ix5GLmGHOZiGl4szaN9Jv0VdvKLcJcTnCh0BlO4IaL4LbDOWfXR/zelx5gaccKTz95hNMnTrO2+gpbww0mdcnGWFldg/UNn+jU1jXS1LBhp1HtLdY5nGSMp8rmBgw3LZYsYlUgUNeWfHGBL375qxw7vsF1h/r8rcuU8dhh2A6QpIhUx9epICqYtpqTDo4fwx7Oa4RoyPKm8NaDljzLuP/bT/DMCyeYjtZYPXuKjfUzDEdbTOuKzVHG/uuu5aOfuYebPvROJsUCtTPB8UX1t63qOwWTMZ0YDt/0Bj7x2/fylp+9G1sv4aTnD0Ed6hy9uT5HXzjKg99/mN0rGTcfVnTqtRRLg1rJzIYjpBa1AVXyeDIpDIrOwDXOO0OrSk/gxv3+1t/+7hNMJhNGww2q2m/IIlRuQH/PPt776b/DygUL7P+Zqzlxasyz3/wW83MG54K9iU90UEXFUNeGhfMP8L7/9I9ZuWgHBz74Bk6enXLkq3/G3GKG2jo0aQSs46EfPMaH734bV+0XjCrOepcnBjDSwR5mq1wNodIH0eZhQnqbPGJ563xBs9SHg3sFp8pTz7yAqmU6GfpQVxbU1lEUwtyFF3FqxxyPnhrzTKUMXnsZdT3XFELqLGotah3OKoqhLnMWDhzm+I5FHj4x4qlK6V91GNw8mLwxBVUgM/zkuZeYFnDhbsPSQKnLkLWGPKXJY1xIixMcUwLClbeApbYRMkmaJWloVBXsHsDeHYaNrYJTp84i1FTlFA0aos7gXMaw7PHcllIVhmworBY9kDmc+oJrtjpRDJAzcXMc3VLsNCPbFNa3DJgBquNQ0xuvq5nhlTNrTMYFK0uGhYFlPaTmOPUpr22xP5mB+mK2m0usnaULgjTARRJTnRPmMmWhb3jlbMFoNEZdja0Fh6BqcFSoU4pKOH0WXAmmgvFIULIE829TNQ+dCUiPSvucXRXcOH7PgMnaeB6FYgzDyZRpUdLrzTHo4f1ACtpKhKklKfm7kHxO2tJKENUWj+8CnVlwtdZa6rrE2QprQdWgkqHiUFdhpyVbJ6EuwGxCsWVBa5/7W+cRPZlFdByuVDaPg06BLSi2KkRc01DRWMYlWZ7GitWGok0EifBbAtG3UHrbCM47uFw8I+22pzTBDCYlTEul1+uR53nI6DIU1/Za3AQ3GbN10uC2HCxCsV5hdIwEGCl1vP43aoQCNx2zdczA2MIyVJsVQhnSZNfWKs6xvLTI3GDAZF2ZFiHZc/FsYo8zpMBOGzevsf8QDK+tjbUFOtJ2eOyBZgY2JnBmy7FreYFdKzuoyhIIcd35QkakxB4/wujxk0xGC4yOKvWRxzFmBK4Oeb/6jDOENmyNSIU98SyTH59hOl1k/EJFdeQJTDYFV3WkIZVj//6LWVjsc2rNsjUJAEvAAaRpsylUoYS3IDaYhfUak0f1cClwNIPjx3KxnytnN4SnTzpes6/H1Vce4pGHH4PFuZA+q09rVZD6Zaqvfx4u+Sn07HHk9BOImaC2QNQF1DFtK9WIEczkJdz//Bx64Dr01AuYVx5DpERtFcgBvvxVC7fefD1ZBkeOOiYT2Lnc5v0qilQKw9rvYmAaHDDtReSpeisJzCVdLUAVg1Cp8lfPwJ0/BX/7Z97GH/63r4diJiJEtU+ejMUMj6A//BEmyyAXtC68GGJW1tikP36tpyAW2fgRnPkhkhnIFHUV4nwunhmhGE24+LWHuPPdb+HMuuU7TyqSSxv/rcLEoUXIbLJYxXagEM8PiA0HdRHu8mCH0w4aHtAUWF6EbzxhOHa25N3vuIEP3f1eRifOYsQDkxrhIjcBHSG9GpEpUo9AS9TVXu2jTYdn/z0HrkCYhu8ViJ0irkRQv/npFGP6/Oav/Tx79u7iwacKvvO4Y3HZ4ETQiUXXKpi4JsZqgO3UBbOLkJ6DbNfbf+03IvsjpsO+VZYADOI9a1UqdgrPvQhzAu+8Fm58w428dHKVx3/wI+q6JssNWeYhKEOsxlxoemqD00nSco0OV8QggBGHQT1SjIJzlEVJPZqw76IDfOYzv8zb3vYmTp4p+PX/WnNsM2N+3qDDCpn65oMYme2YJwlQUi0e/M1SZwkuzgl57lFYZ6AsYDIUqim4yp9cOVT+88fhA7cY1kaGr339//DFP/oGjz52hHJr6NUqM95gMxMO1IRfNcHfuA6XwQXv7glAzoOOCDI/x+FDl3DzbW/i7g++j4svOp+nnp/wxW9W3P9DWNlpkML6RooY3yeIeU2ICmJkpvcRni+9r+rSC4Lq9wa++hlvQTGVYNdtsVFMQArl039X+dCtwtJSn43Nmh/9+Dkef+IZnn72RV46dpqzq+tsbg2ZTKZUVYW1vs4n9BxFhMxkHhTt5fT7fZZ3LLBn1zIX7tvLwcsOcOWVl9PbdZg95y1x46WOhX7F/Q8p7/nFMf0FqEY1Wgsy32dl0fjNSkus6AKh0ukAy4F/XepsERRT5mIi2EoxeURV/Ym6gApVhTLcVO64Cu65Xbn+oGHvzj69vhdiUUJZlkymJVXl8T6PA6hHmFQRDCYzZMaQ5TlZnjM/1yfP+2CgqOGvfwL9rOa919fM94WyFhbmDP/rexXv/+RZ7nr3Ine+ccADj1q+/C3HwoLpZI4djkLKQ0CQi/5VpdtsBSjLgAoHUlRzOxepAR4tVqusbyh5pVxzoeP1h+Dq/XBgL5y/0zDoGeYyYaEf7FIijO01PNLyvOYrRaWsDpVRYTm5pnznSctt1+Z84l056hTr/HdrpyzNZ/zptwvO22W4+Zo+f/FIyR3/YsziYh5S6+0kjbQzpCrkrk7DQpdh0zgSaft8UZmig8QIu5YFWyuPvwKPvOh3szyniLNceZ6y750DTowMKyPHwEFW+x5DhLwqB9Na2HIw3CFcWFme+c6E4yeVT35kwCfekVPV+M1HzRZhfex4z+19NraU46uWtZF3uM7NdIID5K0xnU6knceuDylbLHSAWkRVO1Q4STq9/q4+Bi8tZjDvG5hrq45bDsG/+1jGmSXDF47CkdOGM5u+81NOwdW+8ZlnytIc7FkSrtmn3NTPWSnnefNhuPfuHsNCmcsgH8w0k5wwGnvftHOHUBRKObXMz2c4NZ1WQITKXQcTVnLnZEb23SJITGg6RnBRurw7IyGNEX9zk8HGpvCW1xn+9Fcz8hwmQ3j7bjhbKRsljGqYVN4EnPWm1AOkdAxHcOQM/Mrfy7n5oDCc+sN5fhW++Sw8sipsoOxegpsvUN61T7igB4XCDZdn7N8rHF+r2bHc86X3OUllSWV53qescg4n0GhGwlJrCFUpVy+J5lpDOVUW1fL9z+Zcdj6Mpp6+Uqt3npHmWtf+eVpBWUNRKetj4fiGcv1h4fILYFz4KPpv/xx+67tgFuCaS2HXMrzi4MkSdu6C+66Aj+6FbCA89ZzlA7+8ybE1WFrMcfimiBjjk7wgwVge56qzfEC6tbNLGBqS1AmSwGWF4qYOU1qGJwvu+7kBl+3rMRw7erk/8VzAZh5o1gSo9ZyB0FI3ym1XCft2wuYYlubg7t+Grz8G930Y7rlRKKwyrmHHnM9XPndU+SdPwyrwC7uU1x7M+JPfWuZ9925yZuTo97OW6ktKx5OwLidNBBS69BHSPj4hB/CgjK+wRg43dejEIjhGpeXQPvjYnQOKSjFGAgQWNhxym4H4yq0Km65qrxG9HPbsgCrUL0UFb70K/vm7YGUJPv5V5cEN0DmY3wnvOaR85iq4bQ/MGaiBzQ1lZcmwa1k4saEM+h5tatL5VP29BkhDeVXt0sQa5mdCOnAOdMuiI4eE3akomSjTseX97+2xZ8WwNnRkWUuccuo3nwv80v3KD054iRxcEX79VsUB6yP4k4eUU0O48zph7xJ86g743tNw02fh9dfC790Bly7DQ6vw70/AW5+AH1wN8wKnJsrP/upZnjyqbBWGhUEPa8H0aDBOCTVNZJ/k4lLvrw0+qCR9Nqdo5iEn3bBoGbJC0wKOan1V9cZretROmRRKL5dQVPmYax1MnXLXFfDmA94HzOfKpIRJ4a/ZGMNPTnsnKQKn1mGuD//xg/Cxm+DhY/BXL8I/uAruuBge2ITNEqaZ16Ifv2w5syks7zCBRWZaIlrTIG27xbmHkSTlOzcwE7mA8VwbHVvY8H06Mknopm36nInyPx4oeMeNAwZ9w6RwPn5bn7ho4PtftqBcNq9U1md6G2OYlrA19dcs9Lw2Wusd5AXL8PNvgvuPwAf+SBivKH+2Dv/9VvjIMqzX3jprq8wNhF4/a+l2gYyh2nYKEjYBubNdVn9khzYdogHo2MGGQ400sT/GVfFlHA5hcSnjKw9MefF4yd9/9zzXXj5g705DvydkRhqkelgrtfUUmtqCE8EaxeVQGWFslbL2h2adUNWwOoTTWzCplKUBnK1go4ShU5xCJhK6Twk1TwzGmBZ0bQjT0lJkxCYwuHYZoihoBQytV5+G/iohlQvEKQTJPHK7Y9nw4NMl3398g907Yf/5hov3GvbuylhZzJgbGLLcZ5DOCmUN48L5NtpmzelVy+lXKu6+5nzqnTllMLf1CdxyKfyzW4WHR/CPDkPfqgd8VDHWZ4pIYJVhyLI8AMPSYYc0yLJArnXaLaFTMEhsJYkJfDRpWeNIOy2SGV8bZIJaYWXFgOszKWueeNHy2LPWd1U14dJJylruEiC1VJ4/7rj+KoPJPHMsdrjve6c0KfSwEnYE5zo3EB57pmI49swyYzJMJjg3iwt4bY3MeNn9UaudsZWkbdCApE6hsiizTMeEVqMa6LHtyErDFwxOIpIlPQ+A5ppu714oS8ueHcr73z7PwsAXSSKKVaitX2ntgi0H9CrLhG8/XHLkRcf84oBez2eCzvl+hXbmHpLf2/2RWrdVS5r2zxIyf+1xuYZtrbM203aUTcIxTg/CpWxN2uIqHkgg41IWNcXQBkzOcY7xkKR95f/L5nIWlgb0ellwuILDhHknaTROt/MEuxUSCYum6SYoPqdVE7D9FmhAtUNXFyPJIEVSNCWcsTSKRKVShSx8NpjPmJ9vNSodtJDQKU5Xa4zBZBkiEvjcqePrUgelCYkaJ0Y0GUyKdVKLn7TjYfFGOeA8vN1widogk5qIGGnVXFPGtnRx92aiq9Ui59pZJZJDag47vDZGPFMs+IMG2+xwg7Up45tJFxq6fNo9kwQ8koYoJdLtqnhGkk8NVWg5xYknkXTCJK3DEjJnSonv1GqSkHwlGbSLwwKkTVaPZrt0jCFOs0ji1OMepD33PI6QIbEzLGwbVJMZsCQsTF2UcAd3aE48HVPpVJUzM1DtQWgnRHVnd6Q7vqPtcIV3csk8UlL4kLTHNB2FDO9yUWl6aXEHsq2ObpslTbLUwObSgbdjHSkz0yspHtsg9jGvEG0zNVH0nJMrLV2+NadkDilt6pxjDqkrHC9gCYluo4YdtZdkDE67QVIarm+bW6tI6jpnQAhJzKfL1Gyo802Z3HYMNKSwmr5v/pbODkg699YOfkRNEA2HTYf9BkouqSfvwBuRYNyVb3qwMhMl9JyTrNJJHTTx+i1wJ002KqozVKeuG28jj8zMhyVRKB32TCizngeROGuUXJPNSjLjE/1BO2WVMDBn2Vi8OgDbkphnBqOlO/DY9TlJe15oM88kRCuyjfa6bYKuwQN1+0Bp+A0TU17pTDPr9pZSBEe3/UL6Q9sGSptYnCYtmq5GXm0OuB2b6UxZJ9wCEeFccB5JOI3+S4l+SztrNDKz03S8pIG+Y96vsn23co6BhMTURdJZfGljeuDxN/yDdN6yM+Wm/68tngPSP9fcqCK6be4KFP4vQ2Te9fsLypAAAAAASUVORK5CYII=" alt="" aria-hidden="true">
    小度授权
  </div>
  <div class="summary">
    <div>授权小度访问以下设备：</div>
    <strong>__ENTITY_SUMMARY__</strong>
    <div class="summary-hint">可在集成选项中调整包含 / 排除范围</div>
  </div>
  <p class="subtitle">__SUBTITLE__</p>
  <form method="post" action="__ACTION__" novalidate>
    <input type="hidden" name="response_type" value="code">
    <input type="hidden" name="client_id" value="__CLIENT_ID__">
    <input type="hidden" name="redirect_uri" value="__REDIRECT_URI__">
    <input type="hidden" name="state" value="__STATE__">
    __FIELDS__
    __ERROR__
    <button type="submit" class="submit">__SUBMIT__</button>
  </form>
</main>
</body>
</html>
"""


def _esc(value: Any) -> str:
    return html.escape(str(value), quote=True)


def _get_entry(hass: HomeAssistant) -> ConfigEntry | None:
    """Return the single Xiaodu config entry, if any."""
    entries = hass.config_entries.async_entries(DOMAIN)
    return entries[0] if entries else None


def _callback_origin(redirect_uri: str) -> str:
    """Return the scheme://netloc of the callback URL (used as OAuth client id)."""
    parts = urlparse(redirect_uri)
    return f"{parts.scheme}://{parts.netloc}"


def _redirect_uri_allowed(requested: str, configured: str) -> bool:
    """Accept the configured callback, or the same path on a known Xiaodu host.

    The Xiaodu console uses ``xiaodu.baidu.com`` in production and
    ``xiaodu-dbp.baidu.com`` for debug / mock testing; both are accepted so
    the console environment does not require a reconfigure.
    """
    if requested == configured:
        return True
    try:
        req = urlparse(requested)
        conf = urlparse(configured)
    except ValueError:
        return False
    return (
        req.scheme == "https"
        and (req.hostname or "") in CALLBACK_HOSTS
        and req.path == conf.path
        and not req.query
    )


async def _get_store(hass: HomeAssistant) -> XiaoduOAuthStore:
    """Return the shared OAuth store, loading persisted tokens on first use."""
    data = hass.data.setdefault(DOMAIN, {})
    if DATA_OAUTH_STORE not in data:
        store = XiaoduOAuthStore()
        storage = Store[dict[str, Any]](hass, STORAGE_VERSION, STORAGE_KEY)
        store.load_dict(await storage.async_load())
        data[DATA_OAUTH_STORE] = store
        data[DATA_OAUTH_STORAGE] = storage
    return data[DATA_OAUTH_STORE]


async def _save_store(hass: HomeAssistant) -> None:
    """Persist the current token store."""
    storage: Store[dict[str, Any]] = hass.data[DOMAIN][DATA_OAUTH_STORAGE]
    store: XiaoduOAuthStore = hass.data[DOMAIN][DATA_OAUTH_STORE]
    await storage.async_save(store.to_dict())


def _exposed_device_summary(hass: HomeAssistant, entry: ConfigEntry) -> str:
    """Return a human-readable summary of devices exposed to Xiaodu."""
    enhanced = hass.data.get(DOMAIN, {}).get(DATA_ENHANCED_DEVICES)
    if enhanced is None:
        from .dueros.enhanced import build_enhanced_for_hass  # noqa: PLC0415

        enhanced = build_enhanced_for_hass(hass, entry)
    if not enhanced:
        return "0 台设备（当前没有可暴露的设备）"
    parts: list[str] = []
    for dev in enhanced.all():
        labels = [CAP_LABELS[c.key] for c in dev.capabilities if c.key in CAP_LABELS]
        if labels:
            parts.append(f"{dev.friendly_name}（{'、'.join(labels)}）")
    text = "、".join(parts[:6])
    if len(parts) > 6:
        text += " 等"
    return f"{len(enhanced.all())} 台设备：{text}"


# ---------------------------------------------------------------------------
# Session / CSRF helpers
# ---------------------------------------------------------------------------


def _sessions(hass: HomeAssistant) -> dict[str, dict[str, Any]]:
    """Return the per-instance authorization session table.

    Lives in ``hass.data`` so its lifecycle matches the config entry: unload
    tears it down and multiple entries (if ever allowed) stay isolated.
    """
    return hass.data.setdefault(DOMAIN, {}).setdefault(DATA_AUTH_SESSIONS, {})


def _failures(hass: HomeAssistant) -> dict[str, list[float]]:
    """Return the per-instance login failure throttle table."""
    return hass.data.setdefault(DOMAIN, {}).setdefault(DATA_FAILED_ATTEMPTS, {})


def _new_session(hass: HomeAssistant) -> str:
    """Create a short-lived authorization session and return its nonce."""
    nonce = secrets.token_urlsafe(24)
    _sessions(hass)[nonce] = {"flow_id": None, "expires_at": time.time() + SESSION_TTL}
    return nonce


def _get_session(hass: HomeAssistant, nonce: str) -> dict[str, Any] | None:
    sessions = _sessions(hass)
    session = sessions.get(nonce)
    if session is None or session["expires_at"] <= time.time():
        sessions.pop(nonce, None)
        return None
    return session


def _delete_session(hass: HomeAssistant, nonce: str) -> None:
    _sessions(hass).pop(nonce, None)


def _login_throttled(hass: HomeAssistant, remote_addr: str) -> bool:
    """Return True when the client has too many recent failed attempts."""
    failures = _failures(hass)
    now = time.time()
    attempts = [
        t for t in failures.get(remote_addr, []) if now - t < LOGIN_ATTEMPT_WINDOW
    ]
    failures[remote_addr] = attempts
    return len(attempts) >= LOGIN_ATTEMPT_LIMIT


def _record_failure(hass: HomeAssistant, remote_addr: str) -> None:
    _failures(hass).setdefault(remote_addr, []).append(time.time())


def _clear_failures(hass: HomeAssistant, remote_addr: str) -> None:
    _failures(hass).pop(remote_addr, None)


# ---------------------------------------------------------------------------
# Form rendering
# ---------------------------------------------------------------------------


def _schema_fields(schema: Any) -> list[dict[str, Any]]:
    """Convert a flow data schema into renderable fields."""
    if schema is None:
        return []
    try:
        return voluptuous_serialize.convert(schema)
    except Exception:  # noqa: BLE001 - never break the authorize page
        return []


def _render_field(field: dict[str, Any]) -> str:
    name = str(field.get("name", ""))
    label = _FIELD_LABELS.get(name, name)
    ftype = field.get("type", "string")
    default = field.get("default", "")
    if ftype == "boolean":
        checked = " checked" if default else ""
        return (
            f'<label class="field field-check">'
            f'<input type="checkbox" name="{_esc(name)}"{checked}> '
            f'<span>{_esc(label)}</span></label>'
        )
    input_type = (
        "password"
        if "password" in name.lower()
        else ("number" if ftype == "integer" else "text")
    )
    value = _esc(default) if default not in (None, "") else ""
    autofocus = " autofocus" if name == "username" else ""
    return (
        f'<label class="field">'
        f'<span class="field-label">{_esc(label)}</span>'
        f'<input class="input" name="{_esc(name)}" type="{input_type}" '
        f'value="{value}"{autofocus}>'
        f'</label>'
    )


def _render_fields(fields: list[dict[str, Any]]) -> str:
    if not fields:
        fields = [
            {"name": "username", "type": "string", "required": True},
            {"name": "password", "type": "string", "required": True},
        ]
    return "".join(_render_field(field) for field in fields)


def _map_errors(errors: dict[str, Any] | None) -> str:
    if not errors:
        return ""
    base = str(errors.get("base", ""))
    if base in ("invalid_auth",):
        return "用户名或密码错误"
    if base in ("invalid_code",):
        return "验证码错误"
    return "登录失败，请重试"


class XiaoduOAuthAuthorizeView(HomeAssistantView):
    """Handle requests to the OAuth2 authorize endpoint."""

    url = OAUTH_AUTHORIZE_PATH
    name = "api:xiaodu:oauth:authorize"
    requires_auth = False

    async def get(self, request: web.Request) -> web.Response:
        """Show the first login/consent page."""
        return await self._handle(request, submitted=False)

    async def post(self, request: web.Request) -> web.Response:
        """Progress the login flow and redirect back on success."""
        return await self._handle(request, submitted=True)

    async def _handle(self, request: web.Request, submitted: bool) -> web.Response:
        hass = request.app["hass"]
        entry = _get_entry(hass)
        if entry is None:
            return web.Response(text="Xiaodu is not configured.", status=400)

        params = dict(request.query)
        if submitted:
            params.update(await request.post())

        client_id = entry.data.get(CONF_CLIENT_ID)
        configured_redirect = entry.data.get(CONF_REDIRECT_URI)
        redirect_uri = params.get("redirect_uri", "")
        state = params.get("state", "")

        # ``state`` is required (Xiaodu always sends it) and validated on
        # every step of the flow. The redirect URI may use either the
        # production or the debug Xiaodu host.
        if (
            params.get("response_type") != "code"
            or params.get("client_id") != client_id
            or not _redirect_uri_allowed(redirect_uri, configured_redirect)
            or not state
        ):
            return web.Response(text="Invalid authorization request.", status=400)

        summary = _exposed_device_summary(hass, entry)

        if not submitted:
            nonce = _new_session(hass)
            return self._page(
                client_id,
                redirect_uri,
                state,
                summary=summary,
                fields=[],
                subtitle=_SUBTITLE_LOGIN,
                submit="登录并授权",
                error="",
                nonce=nonce,
            )

        remote_addr = request.remote or ""
        if _login_throttled(hass, remote_addr):
            return self._page(
                client_id,
                redirect_uri,
                state,
                summary=summary,
                fields=[],
                subtitle=_SUBTITLE_LOGIN,
                submit="登录并授权",
                error="尝试次数过多，请稍后再试",
                nonce="",
            )

        nonce = request.cookies.get(SESSION_COOKIE, "")
        session = _get_session(hass, nonce)
        if session is None:
            return web.Response(text="授权会话已过期，请重新打开授权页。", status=400)

        try:
            result = await self._progress_flow(
                hass, request, redirect_uri, session, params
            )
        except (ValueError, KeyError) as err:
            _LOGGER.warning("Xiaodu authorize flow failed: %s", err)
            _delete_session(hass, nonce)
            return self._page(
                client_id,
                redirect_uri,
                state,
                summary=summary,
                fields=[],
                subtitle=_SUBTITLE_LOGIN,
                submit="登录并授权",
                error="授权流程异常，请重新打开授权页",
                nonce="",
            )

        if result["type"] == "create_entry":
            credentials = result.get("result")
            if credentials is None:
                _delete_session(hass, nonce)
                return self._page(
                    client_id,
                    redirect_uri,
                    state,
                    summary=summary,
                    fields=[],
                    subtitle=_SUBTITLE_LOGIN,
                    submit="登录并授权",
                    error="登录未完成，请重试",
                    nonce="",
                )
            user = await hass.auth.async_get_user_by_credentials(credentials)
            user_id = user.id if user else ""
            _clear_failures(hass, remote_addr)
            _delete_session(hass, nonce)
            _LOGGER.info("Xiaodu bound by user %s", user_id or "unknown")

            store = await _get_store(hass)
            code = store.issue_code(client_id, redirect_uri, user_id)
            query = {"code": code}
            if state:
                query["state"] = state
            response = web.HTTPFound(f"{redirect_uri}?{urlencode(query)}")
            response.headers["Set-Cookie"] = _clear_cookie()
            return response

        if result["type"] == "form":
            fields = _schema_fields(result.get("data_schema"))
            error = _map_errors(result.get("errors"))
            if error:
                _record_failure(hass, remote_addr)
            is_login = bool(fields) and fields[0].get("name") in ("username", "password")
            return self._page(
                client_id,
                redirect_uri,
                state,
                summary=summary,
                fields=fields,
                subtitle=_SUBTITLE_LOGIN if is_login else _SUBTITLE_MFA,
                submit="登录并授权" if is_login else "继续",
                error=error,
                nonce=nonce,
            )

        # aborted / unexpected
        _delete_session(hass, nonce)
        return self._page(
            client_id,
            redirect_uri,
            state,
            summary=summary,
            fields=[],
            subtitle=_SUBTITLE_LOGIN,
            submit="登录并授权",
            error="授权已取消，请重试",
            nonce="",
        )

    @staticmethod
    async def _progress_flow(
        hass: HomeAssistant,
        request: web.Request,
        redirect_uri: str,
        session: dict[str, Any],
        params: dict[str, Any],
    ) -> dict[str, Any]:
        """Start or advance the login flow and return the raw flow result."""
        flow_mgr = hass.auth.login_flow
        client_id_origin = _callback_origin(redirect_uri)
        if not indieauth.verify_client_id(client_id_origin):
            raise ValueError("invalid client id")

        if session.get("flow_id") is None:
            result = await flow_mgr.async_init(
                ("homeassistant", None),
                context=AuthFlowContext(
                    ip_address=ip_address(request.remote),
                    redirect_uri=redirect_uri,
                ),
            )
            if result.get("type") != "form":
                raise ValueError(result.get("errors") or "login flow did not start")
            session["flow_id"] = result["flow_id"]

        user_input = {
            key: value
            for key, value in params.items()
            if key not in _FIXED_PARAMS
        }
        return await flow_mgr.async_configure(session["flow_id"], user_input)

    @staticmethod
    def _page(
        client_id: str,
        redirect_uri: str,
        state: str,
        summary: str,
        fields: list[dict[str, Any]],
        subtitle: str,
        submit: str,
        error: str,
        nonce: str,
    ) -> web.Response:
        page = (
            _PAGE.replace("__ACTION__", _esc(OAUTH_AUTHORIZE_PATH))
            .replace("__CLIENT_ID__", _esc(client_id or ""))
            .replace("__REDIRECT_URI__", _esc(redirect_uri or ""))
            .replace("__STATE__", _esc(state))
            .replace("__ENTITY_SUMMARY__", _esc(summary))
            .replace("__SUBTITLE__", _esc(subtitle))
            .replace("__FIELDS__", _render_fields(fields))
            .replace("__SUBMIT__", _esc(submit))
            .replace(
                "__ERROR__",
                f'<div class="error">{_esc(error)}</div>' if error else "",
            )
        )
        headers = {}
        if nonce:
            headers["Set-Cookie"] = (
                f"{SESSION_COOKIE}={nonce}; Path={OAUTH_AUTHORIZE_PATH}; "
                f"HttpOnly; SameSite=Strict; Max-Age={SESSION_TTL}"
            )
        else:
            headers["Set-Cookie"] = _clear_cookie()
        return web.Response(
            text=page, content_type="text/html", charset="utf-8", headers=headers
        )


def _clear_cookie() -> str:
    return f"{SESSION_COOKIE}=; Path={OAUTH_AUTHORIZE_PATH}; Max-Age=0"


class XiaoduOAuthTokenView(HomeAssistantView):
    """Handle requests to the OAuth2 token endpoint."""

    url = OAUTH_TOKEN_PATH
    name = "api:xiaodu:oauth:token"
    requires_auth = False

    async def post(self, request: web.Request) -> web.Response:
        """Exchange a code or refresh token for an opaque access token."""
        hass = request.app["hass"]
        entry = _get_entry(hass)
        if entry is None:
            return web.json_response({"error": "invalid_client"}, status=400)

        data = await self._parse_data(request)
        status, body = await self._exchange(hass, entry, data)
        _access_log(
            "token",
            grant_type=data.get("grant_type"),
            client_id=data.get("client_id"),
            status=status,
            result=body.get("error", "ok"),
        )
        return web.json_response(body, status=status)

    @staticmethod
    async def _exchange(
        hass: HomeAssistant, entry: ConfigEntry, data: dict[str, Any]
    ) -> tuple[int, dict[str, Any]]:
        """Perform the token exchange; return (http_status, body)."""
        if (
            data.get("client_id") != entry.data.get(CONF_CLIENT_ID)
            or data.get("client_secret") != entry.data.get(CONF_CLIENT_SECRET)
        ):
            return 400, {"error": "invalid_client"}

        store = await _get_store(hass)
        grant_type = data.get("grant_type")

        if grant_type == "authorization_code":
            code = data.get("code")
            record = store.consume_code(code) if code else None
            if record is None or data.get("redirect_uri") != record["redirect_uri"]:
                return 400, {"error": "invalid_grant"}
            access, refresh = store.issue_token(
                record["client_id"], record.get("user_id")
            )
        elif grant_type == "refresh_token":
            rotated = store.rotate_token(data.get("refresh_token", ""))
            if rotated is None:
                return 400, {"error": "invalid_grant"}
            access, refresh = rotated
        else:
            return 400, {"error": "unsupported_grant_type"}

        await _save_store(hass)
        return 200, {
            "access_token": access,
            "token_type": "Bearer",
            "expires_in": OAUTH_ACCESS_TOKEN_EXPIRE_SECONDS,
            "refresh_token": refresh,
        }

    @staticmethod
    async def _parse_data(request: web.Request) -> dict[str, Any]:
        if request.content_type == "application/json":
            try:
                return await request.json()
            except (json.JSONDecodeError, ValueError):
                pass
        return dict(await request.post())


async def _process_dueros_request(
    hass: HomeAssistant,
    request: web.Request,
    data: dict[str, Any],
    started: float,
) -> dict[str, Any]:
    """Validate the token and dispatch one DuerOS smart-home request.

    Shared by the plain JSON endpoint (``/api/xiaodu``) and the Baidu console
    DCS multipart endpoint (``/api/xiaodu/service``). Returns the response
    dict; the caller decides how to serialize it.
    """
    store = await _get_store(hass)
    header = data.get("header") or {}
    payload = data.get("payload") or {}
    message_id = header.get("messageId", "")
    namespace = header.get("namespace", "")
    name = header.get("name", "")
    entity_id = (payload.get("appliance") or {}).get("applianceId", "")

    token = payload.get("accessToken") or ""
    if not token:
        auth = request.headers.get("Authorization", "")
        if auth.lower().startswith("bearer "):
            token = auth[7:].strip()

    if not store.validate_token(token):
        _LOGGER.warning(
            "Xiaodu DuerOS request rejected (invalid token), messageId=%s",
            message_id,
        )
        _log_dueros(
            request, started, message_id, namespace, name, entity_id,
            result="ACCESS_TOKEN_INVALIDATE", status=401,
        )
        return {"error": "ACCESS_TOKEN_INVALIDATE"}

    entry = _get_entry(hass)
    if entry is None:
        _log_dueros(
            request, started, message_id, namespace, name, entity_id,
            result="ACCESS_TOKEN_INVALIDATE", status=401,
        )
        return {"error": "ACCESS_TOKEN_INVALIDATE"}

    if namespace == NAMESPACE_UNBIND and name == "UnbindBotRequest":
        # User unbundled the skill in the Xiaodu store: revoke the token and
        # drop the openUid bound to that user so device sync stops targeting
        # them. user_id must be read before the token record is revoked.
        user_id = store.user_id_for_token(token)
        store.revoke(token)
        if user_id:
            store.remove_open_uid(user_id)
        await _save_store(hass)
        _log_dueros(
            request, started, message_id, namespace, name, entity_id,
            result="UnbindBotResponse", status=200,
        )
        response_header = dict(header)
        response_header["name"] = "UnbindBotResponse"
        return {"header": response_header, "payload": {}}

    open_uid = payload.get("openUid") or ""
    if namespace == NAMESPACE_DISCOVERY and open_uid:
        user_id = store.user_id_for_token(token)
        if store.record_open_uid(user_id, open_uid):
            await _save_store(hass)
            _LOGGER.info("Xiaodu recorded openUid %s (user %s)", open_uid, user_id or "?")

    enhanced = hass.data.get(DOMAIN, {}).get(DATA_ENHANCED_DEVICES)

    try:
        response = await handle_request(hass, enhanced, data)
        result = (response.get("header") or {}).get("name", "OK")
        status = 200
    except Exception:  # noqa: BLE001 - protocol errors must not 500 the skill
        _LOGGER.exception(
            "Xiaodu DuerOS request failed, messageId=%s",
            message_id,
        )
        response_header = dict(header)
        response_header["name"] = "DriverInternalError"
        response = {"header": response_header, "payload": {}}
        result = "DriverInternalError"
        status = 200

    _log_dueros(
        request, started, message_id, namespace, name, entity_id,
        result=result, status=status,
    )
    return response


def _log_dueros(
    request: web.Request,
    started: float,
    message_id: str,
    namespace: str,
    name: str,
    entity_id: str,
    result: str,
    status: int,
) -> None:
    """Emit one access-log line for a DuerOS request."""
    duration_ms = round((time.perf_counter() - started) * 1000, 1)
    _access_log(
        "dueros",
        messageId=message_id,
        namespace=namespace,
        name=name,
        entity=entity_id,
        result=result,
        status=status,
        ms=duration_ms,
        ip=request.remote,
        xff=request.headers.get("X-Forwarded-For", "").split(",")[0].strip(),
    )


class XiaoduDuerOSView(HomeAssistantView):
    """Plain-JSON DuerOS smart-home endpoint (production shape).

    The Xiaodu skill authenticates every request with the opaque access token
    it received at the token endpoint; the token travels inside the JSON
    payload (``payload.accessToken``), with the ``Authorization`` header kept
    as a fallback. Even with a valid token, requests only operate on entities
    allowed by the entry's device/capability config (least privilege).
    """

    url = DUEROS_API_PATH
    name = "api:xiaodu:dueros"
    requires_auth = False

    async def post(self, request: web.Request) -> web.Response:
        """Handle a plain-JSON DuerOS smart-home request."""
        hass = request.app["hass"]
        started = time.perf_counter()
        data = await _parse_json(request)
        if data is None:
            _access_log(
                "dueros",
                result="INVALID_REQUEST",
                status=400,
                ms=round((time.perf_counter() - started) * 1000, 1),
                ip=request.remote,
                xff=request.headers.get("X-Forwarded-For", "").split(",")[0].strip(),
            )
            return web.json_response({"error": "INVALID_REQUEST"}, status=400)
        response = await _process_dueros_request(hass, request, data, started)
        status = 401 if response.get("error") else 200
        return web.json_response(response, status=status)


class XiaoduDuerOSServiceView(HomeAssistantView):
    """WebService endpoint (``/api/xiaodu/service``) for the Xiaodu console.

    Accepts both shapes:

    - ``application/json``: the production smart-home directive, handled
      exactly like :class:`XiaoduDuerOSView`.
    - ``multipart/form-data``: the Baidu console "模拟测试" DCS envelope.
      The real directive is read from ``metadata.debug.bot.smarthome[0]``,
      processed, and the response is written back to the same slot.
    """

    url = DUEROS_SERVICE_PATH
    name = "api:xiaodu:dueros:service"
    requires_auth = False

    async def post(self, request: web.Request) -> web.Response:
        """Handle a request to the WebService endpoint."""
        hass = request.app["hass"]
        started = time.perf_counter()

        if request.content_type == "application/json":
            data = await _parse_json(request)
            if data is None:
                return _invalid_request(started, request)
            response = await _process_dueros_request(hass, request, data, started)
            status = 401 if response.get("error") else 200
            return web.json_response(response, status=status)

        if request.content_type.startswith("multipart/form-data"):
            envelope = parse_dcs_multipart(
                await request.read(), request.headers.get("Content-Type", "")
            )
            if envelope is None:
                # No smart-home directive inside the DCS envelope (e.g. a pure
                # TTS/audio exchange); acknowledge so the gateway can proceed.
                _access_log(
                    "dueros",
                    result="NO_SMARTHOME_REQUEST",
                    status=200,
                    ms=round((time.perf_counter() - started) * 1000, 1),
                    ip=request.remote,
                    xff=request.headers.get(
                        "X-Forwarded-For", ""
                    ).split(",")[0].strip(),
                )
                return web.json_response({})
            response = await _process_dueros_request(
                hass, request, envelope["smarthome"], started
            )
            if response.get("error"):
                # Token rejection is a hard error for the whole request.
                return web.json_response(response, status=401)
            filled = fill_smarthome_response(envelope["metadata"], response)
            return web.json_response(filled)

        return _invalid_request(started, request)
async def _parse_json(request: web.Request) -> dict[str, Any] | None:
    """Parse the DuerOS JSON body (None when malformed)."""
    try:
        data = await request.json()
    except (json.JSONDecodeError, ValueError):
        return None
    return data if isinstance(data, dict) else None


def _invalid_request(started: float, request: web.Request) -> web.Response:
    """Log and return a 400 INVALID_REQUEST response."""
    _access_log(
        "dueros",
        result="INVALID_REQUEST",
        status=400,
        ms=round((time.perf_counter() - started) * 1000, 1),
        ip=request.remote,
        xff=request.headers.get("X-Forwarded-For", "").split(",")[0].strip(),
    )
    return web.json_response({"error": "INVALID_REQUEST"}, status=400)
